name: ecommerce
description: "A new Flutter ecommerce project"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.1

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^4.6.0
  flutter_svg: ^2.2.4
  cupertino_icons: ^1.0.8
  intl: ^0.20.2

  flutter_localizations:
    sdk: flutter

  # 🔥 Common ecommerce packages
  http: ^1.2.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  cached_network_image: ^3.3.1
  fluttertoast: ^8.2.4
  firebase_crashlytics: ^5.1.0
  firebase_analytics: ^12.2.0
  pin_code_fields:  ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/